-- MySQL Script generated by MySQL Workbench
-- Fri Jun 22 10:48:33 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema goku
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `goku` ;

-- -----------------------------------------------------
-- Schema goku
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `goku` DEFAULT CHARACTER SET utf8 ;
USE `goku` ;

-- -----------------------------------------------------
-- Table `goku`.`model`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `goku`.`model` ;

CREATE TABLE IF NOT EXISTS `goku`.`model` (
  `id` VARCHAR(32) NOT NULL,
  `name` VARCHAR(32) NOT NULL,
  `modified_time` BIGINT NUll,
  `info` MEDIUMBLOB NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `goku`.`model_group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `goku`.`model_group` ;

CREATE TABLE IF NOT EXISTS `goku`.`model_group` (
  `id` VARCHAR(32) NOT NULL,
  `name` VARCHAR(32) NOT NULL,
  `modified_time` BIGINT NUll,
  `info` MEDIUMBLOB NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `goku`.`task`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `goku`.`task` ;

CREATE TABLE IF NOT EXISTS `goku`.`task` (
  `id` VARCHAR(32) NOT NULL,
  `info` MEDIUMBLOB NOT NULL,
  `status` INT NOT NULL,
  `start_time` BIGINT NULL,
  `end_time` BIGINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `goku`.`task_result`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `goku`.`task_result` ;

CREATE TABLE IF NOT EXISTS `goku`.`task_result` (
  `id` VARCHAR(32) NOT NULL,
  `task_id` VARCHAR(32) NOT NULL,
  `start_time` BIGINT NULL,
  `end_time` BIGINT NULL,
  `info` MEDIUMBLOB NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_idx` (`task_id` ASC),
  CONSTRAINT `task_id`
    FOREIGN KEY (`task_id`)
    REFERENCES `goku`.`task` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
